import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.css";
import StatusMenuContextComponent from "@/context/contextSidebar/StatusMenu";
import { AuthProvider } from "@/context/authContext/AuthContext";


const myFont = localFont({
  src: "../../assets/font/Kollektif.woff2",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Área Cliente",
  description: "Generated by create next app",
};

export default function UserPageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <AuthProvider>
        <StatusMenuContextComponent>
          <body className={myFont.className}>{children}</body>
        </StatusMenuContextComponent>
        </AuthProvider>
    </html>
  );
}
