import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../styles/globals.css";
import StatusMenuContextComponent from "@/context/contextSidebar/StatusMenu";
import { AuthProvider } from "@/context/authContext/AuthContext";
import { PropsWithChildren } from "react";
import SideBar from "@/components/sidebar/Sidebar";

const myFont = localFont({
  src: "../../assets/font/Kollektif.woff2",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Área Cliente",
  description: "Generated by create next app",
};

export default function UserPageLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-BR">
      <StatusMenuContextComponent>
        <body className={myFont.className}>
          <AuthProvider>{children}</AuthProvider>
        </body>
      </StatusMenuContextComponent>
    </html>
  );
}
